apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.name" . }}
  {{- if .Values.tls.enabled }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.tls.secretName }}
  {{- end }}
spec:
  selector:
    app: {{ include "app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
