image:
  repository: ghcr.io/andreat2009/tsatech-wishlist-service
  tag: latest
  digest: ""
  pullPolicy: Always

global:
  domain: "apps.example.invalid"
  platformNamespace: "platform"
  appNamespace: "ecommerce"

route:
  enabled: false
  host: ""
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  annotations: {}

ingress:
  enabled: false
  className: nginx
  host: '{{ printf "%s-%s.%s" .Release.Name .Release.Namespace .Values.global.domain }}'
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    enabled: true
    secretName: wildcard-apps-tls

networkPolicy:
  enabled: true
  allowSameNamespace: true
  allowIngressController: false
  ingressControllerNamespace: ingress-nginx

env:
  SERVER_PORT: "8443"
  SERVER_SSL_ENABLED: "false"
  KEYCLOAK_ISSUER_URI: '{{ printf "https://keycloak-%s.%s/realms/ecommerce" .Values.global.platformNamespace .Values.global.domain }}'
  KEYCLOAK_JWK_SET_URI: '{{ printf "http://keycloak.%s.svc.cluster.local/realms/ecommerce/protocol/openid-connect/certs" .Values.global.platformNamespace }}'
  KAFKA_BOOTSTRAP_SERVERS: '{{ printf "keros-kafka.%s.svc.cluster.local:9092" .Values.global.platformNamespace }}'
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"

secret:
  name: wishlist-service-secret
  create: false
  data: {}

secretEnv: {}

tls:
  enabled: false
  secretName: wildcard-apps-tls

truststore:
  enabled: false
  secretName: platform-truststore
  mountPath: /etc/ssl/openshift
  password: changeit

readinessProbe:
  scheme: HTTP
  path: /actuator/health
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  scheme: HTTP
  path: /actuator/health
  initialDelaySeconds: 120
  periodSeconds: 20
