replicaCount: 1
image:
  repository: image-registry.openshift-image-registry.svc:5000/ecommerce/wishlist-service
  tag: "latest"
  digest: ""
  pullPolicy: IfNotPresent

service:
  port: 8443

route:
  enabled: true
  host: "wishlist-service-ecommerce.apps-crc.testing"
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  annotations: {}

env:
  SERVER_PORT: "8443"
  SERVER_SSL_ENABLED: "true"
  KEYCLOAK_ISSUER_URI: "https://keycloak-platform.apps-crc.testing/realms/master"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.platform.svc.cluster.local:9092"
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"

secret:
  name: "wishlist-service-secret"
  create: false
  data: {}
  # data example:
  #   DB_HOST: "db"
  #   DB_PORT: "5432"
  #   DB_NAME: "wishlist-service"
  #   DB_USER: "wishlist-service"
  #   DB_PASSWORD: "change-me"

secretEnv:
  {}

tls:
  enabled: true
  secretName: "wildcard-apps-tls"

truststore:
  enabled: true
  secretName: "platform-truststore"
  mountPath: "/etc/ssl/openshift"
  password: "changeit"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 20
  periodSeconds: 20

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
